name: alumni_management
description: "A new Flutter project for alumni management systemm where backend is on Java spring boot"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.1
  stomp_dart_client: ^3.0.1
  image_picker: ^1.0.4
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
